Updated src/defaults/schema.json
Udayraj123/OMRChecker pull request #115
Opened 2022-12-23 16:06 UTC by rudrapsc

edited schema, now it will show validation error if in the preprocessor the name is not given , options are not given and if the name of the plugin happen to be CropOnMarkers , then relative path becomes a required field and will show error if not given.

removed relative path from the template.json of sample4
![image](https://user-images.githubusercontent.com/114874767/209364920-36ee06d5-829b-47ce-8e8a-a426cb0bd9f3.png)

it showed this error
![image](https://user-images.githubusercontent.com/114874767/209364806-2fa71811-ae25-4889-b376-7d8c96cdd0c3.png)

2022-12-27 08:56 UTC, Udayraj123 commented on src/defaults/schema.json
> +          "enum": ["CropOnMarkers","CropPage","FeatureBasedAlignment","ReadBarcode","GaussianBlur","Levels","MedianBlur"],
format the json - spaces between items

2022-12-27 16:15 UTC, rudrapsc commented
![image](https://user-images.githubusercontent.com/114874767/209692233-c7052754-6a0b-4ece-821f-43e4f31126dd.png)

2022-12-27 19:50 UTC, Udayraj123 commented on src/defaults/schema.json
> +                    }
Add types for min_matching_threshold and others too (float, int, etc)

2022-12-27 19:52 UTC, Udayraj123 commented on src/defaults/schema.json
> +                  "enum": ["morphKernel"]
also define type for morphKernel as a 2-sized array

2022-12-27 19:52 UTC, Udayraj123 commented on src/defaults/schema.json
> +                  "enum": ["relativePath","min_matching_threshold","max_matching_variation","marker_rescale_range",
Do the space formatting changes too (use json beautifier)

2022-12-28 04:27 UTC, Udayraj123 requested changes
Suggested few more changes. Also add 1-2 more screenshots of invalid jsons

2022-12-28 04:27 UTC, Udayraj123 commented on src/defaults/schema.json
> +                      "maxItems": 2
```suggestion
                      "minItems": 2,
                      "maxItems": 2
```

2022-12-28 04:27 UTC, Udayraj123 commented on src/defaults/schema.json
> +                      "type": "number"
okay, so "number" allows floats + integers both, cool

2022-12-28 04:27 UTC, Udayraj123 commented on src/defaults/schema.json
> +                      "prefixItems": [
Why do we need prefixItems if type of both items is integer?

2022-12-28 04:27 UTC, Udayraj123 commented on src/defaults/schema.json
> +                      "maxItems": 2
add minItems = 2 as well

2022-12-28 04:27 UTC, Udayraj123 commented on src/defaults/schema.json
> +        "required": [
move this key to the top before "allOf"

2022-12-28 10:28 UTC, rudrapsc commented
![image](https://user-images.githubusercontent.com/114874767/209797893-b87d23e6-8117-4de8-9504-a14e35ca0d66.png)

this screenshot shows three invalid json ,one with array length greater than the max , one with array length shorter than given min and one with garbage options.

2022-12-28 22:50 UTC, Udayraj123 commented
Okay, the key column seems not specific to the error path

2022-12-28 23:02 UTC, Udayraj123 commented
Can you make the following change in `src/utils/file.py` and share the output with me?
```python
key, validator, msg = error.path, error.validator, error.message
# print the error paths
print(error.path)
print(error.absolute_path)
```

ref: https://python-jsonschema.readthedocs.io/en/latest/errors/

2022-12-29 12:59 UTC, rudrapsc commented
> Can you make the following change in `src/utils/file.py` and share the output with me?
> 
> ```python
> key, validator, msg = error.path, error.validator, error.message
> # print the error paths
> print(error.path)
> print(error.absolute_path)
> ```
> 
> ref: https://python-jsonschema.readthedocs.io/en/latest/errors/

![image](https://user-images.githubusercontent.com/114874767/209954450-05c8292d-ddbe-49e6-988d-850bf6efbac4.png)

this is the output i received

2022-12-29 13:20 UTC, Udayraj123 commented
<img width="836" alt="image" src="https://user-images.githubusercontent.com/16881051/209958168-9bf1101d-e32a-429d-a976-013d57070b78.png">
Need to change sigmax in builtins.py

2022-12-29 13:43 UTC, Udayraj123 commented
Changing morphKernel to have 1.0 as one of the values gives this error -
```
TypeError: Can't parse 'ksize'. Sequence item with index 0 has a wrong type

```

2022-12-29 18:35 UTC, merged